# Build the vendored XCPlite subset in xcplite/ into a static library and put
# its headers on the include path.
#
# Keep XCPLITE_SOURCES in sync with the .c files copied by
# tools/update_xcplite.sh.

import hashlib
from pathlib import Path

Import("env")

project_dir = Path(env.subst("$PROJECT_DIR"))
xcplite_inc = project_dir / "xcplite" / "inc"
xcplite_src = project_dir / "xcplite" / "src"

if not xcplite_src.is_dir():
    raise RuntimeError(f"Vendored XCPlite sources not found at {xcplite_src}. Run tools/update_xcplite.sh")

env.Append(CPPPATH=[str(xcplite_inc), str(xcplite_src)])

# The subset of XCPlite needed for a 32-bit FreeRTOS target in the rtos
# configuration. The A2L generator, persistence, shared memory and the 64-bit
# queue variants are disabled by xcplib_rtos_cfg.h and are not built.
XCPLITE_SOURCES = [
    "cal.c",
    "platform.c",
    "queue32m.c",
    "xcpappl.c",
    "xcpethserver.c",
    "xcpethtl.c",
    "xcplite.c",
]

env.BuildSources(
    "$BUILD_DIR/xcplite",
    str(xcplite_src),
    src_filter=["+<{}>".format(source) for source in XCPLITE_SOURCES],
)


# ----------------------------------------------------------------------------
# EPK build identifier
#
# The EPK is the version string CANape and xcpclient use to decide whether an
# A2L still matches the firmware. XcpCreateEpk() places it in the xcp_epk
# section, so it must be a string literal:
#
#   static char gXcpEpkString[] __attribute__((section("xcp_epk"))) = epk;
#
# It therefore has to be produced at build time. We hash the build inputs and
# expose the result as a macro in a generated header, which gives an EPK that
# changes exactly when something that can move addresses changes -- and stays
# stable across rebuilds that change nothing, so a good A2L keeps working.
#
# Deliberately not __DATE__/__TIME__: those only update when the translation
# unit containing them is recompiled, so editing any other file would move
# addresses while the EPK stayed the same.

EPK_HASH_ROOTS = ["src", "include", "xcplite"]
EPK_HASH_FILES = ["platformio.ini", "extra_script.py", "extra_linker_script.py"]


def compute_epk_build_id(project_dir):
    paths = []
    for root in EPK_HASH_ROOTS:
        directory = project_dir / root
        if directory.is_dir():
            paths += [p for p in directory.rglob("*") if p.is_file()]
    for name in EPK_HASH_FILES:
        path = project_dir / name
        if path.is_file():
            paths.append(path)

    digest = hashlib.sha256()
    # Sort by relative path so the result does not depend on filesystem order,
    # and hash the names too so a rename is not invisible.
    for path in sorted(paths, key=lambda p: str(p.relative_to(project_dir))):
        digest.update(str(path.relative_to(project_dir)).encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()[:8]


build_dir = Path(env.subst("$BUILD_DIR"))
epk_header = build_dir / "epk_generated.h"
epk_text = (
    "// Generated by extra_script.py, do not edit.\n"
    "#pragma once\n"
    '#define XCP_EPK_BUILD_ID "{}"\n'.format(compute_epk_build_id(project_dir))
)

# Only rewrite when the value actually changed, otherwise every build would
# recompile the EPK translation unit and relink for nothing.
if not epk_header.exists() or epk_header.read_text() != epk_text:
    epk_header.parent.mkdir(parents=True, exist_ok=True)
    epk_header.write_text(epk_text)

env.Append(CPPPATH=[str(build_dir)])
